# Nombre de la aplicación
spring.application.name=magician-adventure

# Puerto del servidor (8080 es el default)
server.port=8080

# Configuración para ver logs detallados (opcional)
logging.level.org.springframework.web=DEBUG

# Desactivar cache en desarrollo
spring.resources.cache.period=0